openapi: "3.1.0"
info:
  version: "1.0.0"
  title: "Diagnostic API"
  description: "API for diagnostic challenges and system design assessments"
host: "localhost:5000"
basePath: "/api"
schemes:
  - "http"
  - "https"
paths:
  /coding_challenge:
    get:
      summary: "Get a coding challenge"
      description: "Retrieve a coding challenge, optionally filtered by topic."
      parameters:
        - in: query
          name: topic
          description: "Topic to filter the coding challenge by."
          required: false
          type: string
          schema:
            type: string
      responses:
        "200":
          description: "A coding challenge"
          schema:
            type: object
            properties:
              id:
                type: string
              title:
                type: string
              difficulty:
                type: string
              category:
                type: string
              topics:
                type: array
                items:
                  type: string
              company_context:
                type: string
              problem_statement:
                type: string
              input_format:
                type: string
              output_format:
                type: string
              test_cases:
                type: array
                items:
                  type: object
                  properties:
                    input:
                      type: string
                    expected:
                      type: string
                    description:
                      type: string
              follow_up:
                type: array
                items:
                  type: string
        "404":
          description: "No problem found for the given topic."
  /coding_challenges:
    get:
      summary: "Get coding challenges by skill level"
      description: "Retrieve a list of coding challenges filtered by skill level."
      parameters:
        - in: query
          name: level
          description: "Skill level to filter the coding challenges by."
          required: true
          schema:
            type: string
            enum: [entry, intermediate, advanced]
      responses:
        "200":
          description: "A list of coding challenges"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
                difficulty:
                  type: string
                category:
                  type: string
                topics:
                  type: array
                  items:
                    type: string
                company_context:
                  type: string
                problem_statement:
                  type: string
                input_format:
                  type: string
                output_format:
                  type: string
                test_cases:
                  type: array
                  items:
                    type: object
                    properties:
                      input:
                        type: string
                      expected:
                        type: string
                      description:
                        type: string
                follow_up:
                  type: array
                  items:
                    type: string
        "404":
          description: "Invalid skill level."
  /submit_code:
    post:
      summary: "Submit a coding solution"
      description: "Submit a coding solution for evaluation."
      requestBody:
        description: "Coding solution to submit."
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                problem_id:
                  type: string
                code:
                  type: string
      responses:
        "200":
          description: "Submission result"
          schema:
            type: object
            properties:
              problem_id:
                type: string
              results:
                type: array
                items:
                  type: object
                  properties:
                    input:
                      type: string
                    expected:
                      type: string
                    output:
                      type: string
                    passed:
                      type: boolean
                    execution_time:
                      type: number
                    error:
                      type: string
              passed_cases:
                type: integer
              total_cases:
                type: integer
        "400":
          description: "Invalid JSON or missing problem_id or code."
        "404":
          description: "Problem not found."
  /design_questions:
    get:
      summary: "Get system design questions"
      description: "Retrieve a list of system design questions."
      responses:
        "200":
          description: "A list of system design questions"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
                difficulty:
                  type: string
                context:
                  type: string
                requirements:
                  type: object
                  properties:
                    functional:
                      type: array
                      items:
                        type: string
                    non_functional:
                      type: array
                      items:
                        type: string
                evaluation_points:
                  type: array
                  items:
                    type: string
                correct_option:
                  type: string
                options:
                  type: array
                  items:
                    type: string
        "404":
          description: "No system design questions found."
  /submit_design:
    post:
      summary: "Submit system design answers"
      description: "Submit answers to system design questions."
      requestBody:
        description: "System design answers to submit."
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                responses:
                  type: array
                  items:
                    type: object
                    properties:
                      question_id:
                        type: string
                      selected_option:
                        type: string
      responses:
        "200":
          description: "Submission result"
          schema:
            type: object
            properties:
              total_score:
                type: integer
              max_score:
                type: integer
        "400":
          description: "Invalid JSON or no responses provided."
  /diagnostic_report:
    get:
      summary: "Generate a comprehensive diagnostic report"
      description: "Generate a diagnostic report based on coding and design results."
      responses:
        "200":
          description: "Diagnostic report"
          schema:
            type: object
            properties:
              coding:
                type: object
                properties:
                  passed:
                    type: integer
                  total:
                    type: integer
                  percentage:
                    type: number
              design:
                type: object
                properties:
                  score:
                    type: integer
                  total:
                    type: integer
                  percentage:
                    type: number
              overall_recommendation:
                type: string
  /wizard/scenarios:
    get:
      summary: "List all wizard scenarios"
      description: "Retrieve a list of all wizard scenarios."
      responses:
        "200":
          description: "A list of wizard scenarios"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                title:
                  type: string
                description:
                  type: string
  /wizard/scenario/{scenario_id}/steps:
    get:
      summary: "Get steps for a specific wizard scenario"
      description: "Retrieve steps for a specific wizard scenario."
      parameters:
        - in: path
          name: scenario_id
          description: "ID of the wizard scenario."
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "A list of steps for the scenario"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                step_number:
                  type: integer
                title:
                  type: string
                prompt_text:
                  type: string
        "404":
          description: "Scenario not found."
  /wizard/submit_response:
    post:
      summary: "Submit a response for a wizard step"
      description: "Submit a user response for a specific wizard step."
      requestBody:
        description: "Response to submit."
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                scenario_id:
                  type: integer
                step_id:
                  type: integer
                user_response:
                  type: string
      responses:
        "200":
          description: "Response saved"
          schema:
            type: object
            properties:
              message:
                type: string
        "400":
          description: "Missing scenario_id or step_id."
        "500":
          description: "Error storing response."
  /wizard/{scenario_id}/summary:
    get:
      summary: "Get summary of a wizard scenario"
      description: "Retrieve a summary of a wizard scenario including all steps and user responses."
      parameters:
        - in: path
          name: scenario_id
          description: "ID of the wizard scenario."
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Summary of the wizard scenario"
          schema:
            type: array
            items:
              type: object
              properties:
                step_id:
                  type: integer
                step_number:
                  type: integer
                title:
                  type: string
                responses:
                  type: array
                  items:
                    type: string
        "404":
          description: "Scenario not found."
